version: '3.8'

services:
  kc_postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - elba_keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KC_POSTGRES_DB}
      POSTGRES_USER: ${KC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    env_file:
      - .env
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kc_postgres:5432/${KC_POSTGRES_DB}
      KC_DB_USERNAME: ${KC_POSTGRES_USER}
      KC_DB_PASSWORD: ${KC_POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - kc_postgres
    networks:
      - keycloak_network
      
  elba_postgres:
    image: postgres:latest # postgres:16.2
    env_file:
      - .env
    volumes:
      - elba_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - keycloak_network

volumes:
  elba_keycloak_postgres_data:
    driver: local
  elba_postgres_data:
    driver: local
  

networks:
  keycloak_network:
    driver: bridge